import type { Artisan, HeritageLocation, LivelihoodRecord, Product, RecognitionExample, Region, Story, Trail } from './types'
import { heritageTranslations, storyTranslations } from './localized-data'
import { calculateLivelihood } from './livelihood'

const prototypeImage = (name: string) => `/images/${name}.svg`
const officialImageLicense = 'Government site image; reuse permission is not stated — verify before production.'
const commonsLicense = 'CC BY-SA 4.0 — attribution and share-alike terms apply.'
const commonsLicenseBySa3 = 'CC BY-SA 3.0 — attribution and share-alike terms apply.'

const images = {
  brahma: 'https://cdn.s3waas.gov.in/s3248e844336797ec98478f85e7626de4a/uploads/2022/02/2022020411.jpeg',
  jyotisar: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Jyotisar-Kurukshetra-India.jpg',
  sheikh: 'https://cdn.s3waas.gov.in/s3248e844336797ec98478f85e7626de4a/uploads/bfi_thumb/2022011268-1-1024x768-piw4lut75ltl86mggwn4jmpif9ymep6dzc6t1y8v6m.jpg',
  sannihit: 'https://cdn.s3waas.gov.in/s3248e844336797ec98478f85e7626de4a/uploads/bfi_thumb/2018050369-olw848kyckse7fo3f7u41jqt4k21ix2kqt55neallq.jpg',
  karna: 'https://cdn.s3waas.gov.in/s3248e844336797ec98478f85e7626de4a/uploads/2022/03/2022031762.png',
  nabha: 'https://cdn.s3waas.gov.in/s3248e844336797ec98478f85e7626de4a/uploads/2023/01/2023011774-320x220.jpg',
  sthaneshwar: 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Sthaneshwar_mahadev_mandir.jpg',
  rakhigarhi: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Rakhigarhi_The_Oldest_Harappan_civilization.jpg',
  surajkund: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Surajkund_mela.jpg',
  pinjore: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Pinjore_Garden_Panchkula.jpg',
  panipatMuseum: prototypeImage('prototype-panipat-museum'),
  shishMahal: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Sheesh_Mahal_031.jpg',
  food: prototypeImage('prototype-haryana-food'),
}

const sourceUrls = {
  brahma: 'https://haryanatourism.gov.in/places_of_interest/brahma-sarovar/',
  jyotisar: 'https://haryanatourism.gov.in/places_of_interest/jyotisar/',
  sheikh: 'https://haryanatourism.gov.in/places_of_interest/sheikh-chahelis-tomb/',
  sannihit: 'https://haryanatourism.gov.in/places_of_interest/sannihit-sarovar/',
  karna: 'https://haryanatourism.gov.in/places_of_interest/raja-karna-ka-qila/',
  nabha: 'https://haryanatourism.gov.in/places_of_interest/nabha-house/',
  sthaneshwar: 'https://haryanatourism.gov.in/places_of_interest/sthaneshwara-mahadev-temple/',
  rakhigarhi: 'https://haryanatourism.gov.in/places_of_interest/ancient-site-of-rakhigarhi/',
  surajkund: 'https://haryanatourism.gov.in/places_of_interest/surajkund-2/',
  pinjore: 'https://haryanatourism.gov.in/where_to_stay/pinjore-gardens/',
  panipatMuseum: 'https://haryanatourism.gov.in/places_of_interest/panipat-museum/',
  shishMahal: 'https://haryanatourism.gov.in/places_of_interest/shish-mahal/',
}

const imageSourceUrls = {
  brahma: 'https://kurukshetra.gov.in/brahmasarovar/',
  jyotisar: 'https://commons.wikimedia.org/wiki/File:Jyotisar-Kurukshetra-India.jpg',
  sheikh: 'https://kurukshetra.gov.in/gallery/sheikh-chilli-tomb/',
  sannihit: 'https://kurukshetra.gov.in/gallery/sannehit-sarovar-kurukshetra/',
  karna: 'https://kurukshetra.gov.in/raja-karan-ka-qila-mirzapur/',
  nabha: 'https://kurukshetra.gov.in/nabha-house/',
  sthaneshwar: 'https://commons.wikimedia.org/wiki/File:Sthaneshwar_mahadev_mandir.jpg',
  rakhigarhi: 'https://commons.wikimedia.org/wiki/File:Rakhigarhi_The_Oldest_Harappan_civilization.jpg',
  surajkund: 'https://commons.wikimedia.org/wiki/File:Surajkund_mela.jpg',
  pinjore: 'https://commons.wikimedia.org/wiki/File:Pinjore_Garden_Panchkula.jpg',
  panipatMuseum: 'https://haryanatourism.gov.in/places_of_interest/panipat-museum/',
  shishMahal: 'https://commons.wikimedia.org/wiki/File:Sheesh_Mahal_031.jpg',
}

export const regions: Region[] = [
  { id: 'region-kurukshetra', name: 'Kurukshetra', slug: 'kurukshetra', state: 'Haryana', country: 'India', description: 'A Haryana district of sacred water bodies, pilgrimage sites, archaeology and layered cultural memory.', image: images.brahma, imageSource: 'District Administration, Kurukshetra (Government of Haryana)', imageLicense: officialImageLicense, sourceUrl: 'https://haryanatourism.gov.in/destinations/kurukshetra/', latitude: 29.96, longitude: 76.83 },
  { id: 'region-faridabad', name: 'Faridabad', slug: 'faridabad', state: 'Haryana', country: 'India', description: 'A southern Haryana region known here through Surajkund’s craft fair, handwork and performance traditions.', image: images.surajkund, imageSource: 'Wikimedia Commons photograph by Pandey251196', imageLicense: commonsLicense, sourceUrl: sourceUrls.surajkund, latitude: 28.4854, longitude: 77.2852 },
  { id: 'region-panchkula', name: 'Panchkula', slug: 'panchkula', state: 'Haryana', country: 'India', description: 'The foothill setting of Pinjore and its historic garden landscape in Haryana’s Panchkula district.', image: images.pinjore, imageSource: 'Wikimedia Commons photograph by Unpetitprole', imageLicense: commonsLicense, sourceUrl: sourceUrls.pinjore, latitude: 30.7933, longitude: 76.9133 },
  { id: 'region-hisar', name: 'Hisar', slug: 'hisar', state: 'Haryana', country: 'India', description: 'A Haryana region represented by Rakhigarhi’s archaeological landscape and the evidence it continues to reveal.', image: images.rakhigarhi, imageSource: 'Wikimedia Commons photograph by Durgeshkushvaha', imageLicense: commonsLicense, sourceUrl: sourceUrls.rakhigarhi, latitude: 29.17, longitude: 76.07 },
  { id: 'region-haryana', name: 'Haryana', slug: 'haryana', state: 'Haryana', country: 'India', description: 'A statewide view for filtering Haryana’s prototype heritage records together.', image: images.surajkund, imageSource: 'Wikimedia Commons photograph by Pandey251196', imageLicense: commonsLicense, sourceUrl: 'https://haryanatourism.gov.in/', latitude: 29.0588, longitude: 76.0856 },
  { id: 'region-panipat', name: 'Panipat', slug: 'panipat', state: 'Haryana', country: 'India', description: 'A Haryana district represented by Panipat Museum and its public record of archaeology, history, art and craft.', image: images.panipatMuseum, imageSource: 'Jeevant Virasat prototype placeholder', imageLicense: 'Original project SVG; a documentary museum image is pending reuse verification.', sourceUrl: sourceUrls.panipatMuseum, latitude: 29.3833, longitude: 76.9667 },
  { id: 'region-gurugram', name: 'Gurugram', slug: 'gurugram', state: 'Haryana', country: 'India', description: 'A Haryana region represented by Shish Mahal in Farrukhnagar, a protected built-heritage site.', image: images.shishMahal, imageSource: 'Wikimedia Commons photograph by Anupamg', imageLicense: commonsLicenseBySa3, sourceUrl: sourceUrls.shishMahal, latitude: 28.45, longitude: 76.82 },
]

const kurukshetra = regions[0]
const faridabad = regions[1]
const panchkula = regions[2]
const hisar = regions[3]
const haryana = regions[4]
const panipat = regions[5]
const gurugram = regions[6]

const heritageRecords: HeritageLocation[] = [
  {
    id: 'heritage-brahma-sarovar', regionId: kurukshetra.id, regionName: kurukshetra.name, name: 'Brahma Sarovar', slug: 'brahma-sarovar', category: 'Sacred Tradition', district: 'Kurukshetra', state: 'Haryana',
    shortDescription: 'A major sacred water landscape where ritual, walking and public life meet.', description: 'Brahma Sarovar is presented here as a living water edge rather than a backdrop: a place of pilgrimage, movement and repeated community use in Kurukshetra.', culturalSignificance: 'The sarovar’s meaning is carried through worship, bathing, seasonal gatherings and the people who return to its ghats.', historicalContext: 'Haryana Tourism and the District Kurukshetra administration list Brahma Sarovar among the district’s key heritage attractions. This prototype avoids adding unsupported origin claims.', livingToday: 'Observe worship and bathing practices from a respectful distance, follow local photography guidance and keep the water edge clear.',
    image: images.brahma, gallery: [images.brahma], imageSource: 'District Administration, Kurukshetra (Government of Haryana)', imageLicense: officialImageLicense, imageSourceUrl: imageSourceUrls.brahma, sourceUrl: sourceUrls.brahma, latitude: 29.96, longitude: 76.83, coordinateNote: 'Map point is an approximate prototype coordinate; confirm access locally.', durationMinutes: 90, tags: ['water', 'ritual', 'ghats', 'sunrise', 'Kurukshetra'], experienceTypes: ['Quiet & Authentic', 'Photography', 'Deep Historical'], verifiedStatus: 'Official source',
  },
  {
    id: 'heritage-pipli-craft', regionId: kurukshetra.id, regionName: kurukshetra.name, name: 'Pipli’s Appliqué Courtyards', slug: 'pipli-applique-courtyards', category: 'Craft', district: 'Kurukshetra', state: 'Haryana',
    shortDescription: 'A clearly marked prototype prompt for documenting Pipli’s appliqué practice without inventing a maker profile.', description: 'Pipli’s appliqué appears in the prototype as a craft-research record, not as a verified workshop directory or individual biography. The material, maker and consent fields need community review.', culturalSignificance: 'Cut cloth, colour and hand-stitching can connect everyday decoration with social and seasonal life. The platform should document those connections with practitioners.', historicalContext: 'This record is intentionally limited to a Haryana place name and a craft prompt; it makes no unsupported claim about lineage, ownership or current availability.', livingToday: 'Ask before entering a workshop, credit the maker and do not treat a prototype record as a promise of a visit or purchase.',
    image: prototypeImage('prototype-artisan-textile'), gallery: [prototypeImage('prototype-artisan-textile')], imageSource: 'Jeevant Virasat prototype placeholder', imageLicense: 'Original project SVG; no person or specific workshop is depicted.', imageSourceUrl: 'https://haryanatourism.gov.in/destinations/kurukshetra/', sourceUrl: 'https://haryanatourism.gov.in/destinations/kurukshetra/', latitude: 29.9954, longitude: 76.8406, coordinateNote: 'Approximate prototype coordinate for Pipli; verify the workshop and access locally.', durationMinutes: 90, tags: ['textile', 'appliqué', 'handwork', 'Pipli', 'prototype'], experienceTypes: ['Cultural & Social', 'Quiet & Authentic', 'Photography'], verifiedStatus: 'Demonstration content',
  },
  {
    id: 'heritage-kurukshetra-seasonal-food', regionId: kurukshetra.id, regionName: kurukshetra.name, name: 'Kurukshetra Seasonal Food Practice', slug: 'kurukshetra-seasonal-food-practice', category: 'Food', district: 'Kurukshetra', state: 'Haryana',
    shortDescription: 'A research placeholder for documenting seasonal food knowledge without inventing a restaurant or cook.', description: 'This is a demonstration record, not a named kitchen, menu or verified food experience. It keeps the food route testable while local cooks and researchers review future content.', culturalSignificance: 'Food heritage is carried by ingredients, household practice, labour and hospitality. Those details should be documented with consent rather than filled in from generic claims.', historicalContext: 'No single Haryana recipe is treated as representative here. The record is intentionally open until a specific community source and current access details are verified.', livingToday: 'Use the food route as a research prompt, not as a promise of a booking or an invitation to enter a private kitchen.',
    image: images.food, gallery: [images.food], imageSource: 'Jeevant Virasat prototype placeholder', imageLicense: 'Original project SVG; no dish, kitchen or person is depicted.', imageSourceUrl: 'https://haryanatourism.gov.in/', sourceUrl: 'https://haryanatourism.gov.in/', latitude: 29.96, longitude: 76.83, coordinateNote: 'State-level prototype coordinate; not a navigation point.', durationMinutes: 105, tags: ['food', 'seasonal', 'hospitality', 'prototype'], experienceTypes: ['Food-focused', 'Food & Craft', 'Cultural & Social'], verifiedStatus: 'Demonstration content', isHidden: true, hiddenReason: 'A research placeholder until a specific Haryana food practice is community-reviewed.',
  },
  {
    id: 'heritage-jyotisar', regionId: kurukshetra.id, regionName: kurukshetra.name, name: 'Jyotisar', slug: 'jyotisar', category: 'Sacred Heritage', district: 'Kurukshetra', state: 'Haryana',
    shortDescription: 'A pilgrimage landscape at Jyotisar Sarovar, known in Kurukshetra’s sacred geography.', description: 'Jyotisar is a pilgrimage site on the bank of Jyotisar Sarovar. The District Kurukshetra and Haryana Tourism pages frame it as a central place in the district’s religious heritage.', culturalSignificance: 'Visitors encounter a place shaped by prayer, interpretation, trees, water and the continuing rhythm of pilgrimage.', historicalContext: 'The association with the Bhagavad Gita belongs to the site’s religious tradition. The interface labels this as cultural context, not as a claim that replaces community interpretation.', livingToday: 'Dress and move respectfully, leave room for worship and use the site’s own guidance before photographing people or ritual activity.',
    image: images.jyotisar, gallery: [images.jyotisar], imageSource: 'Wikimedia Commons photograph by Nalbarian', imageLicense: commonsLicense, imageSourceUrl: imageSourceUrls.jyotisar, sourceUrl: sourceUrls.jyotisar, latitude: 29.9617, longitude: 76.7708, coordinateNote: 'Coordinate follows the referenced Commons photograph and is approximate for discovery.', durationMinutes: 90, tags: ['pilgrimage', 'sarovar', 'sacred geography', 'Kurukshetra'], experienceTypes: ['Quiet & Authentic', 'Deep Historical', 'Photography'], verifiedStatus: 'Official source',
  },
  {
    id: 'heritage-sheikh-chahelis-tomb', regionId: kurukshetra.id, regionName: kurukshetra.name, name: 'Sheikh Chaheli’s Tomb', slug: 'sheikh-chahelis-tomb', category: 'Architectural Heritage', district: 'Kurukshetra', state: 'Haryana',
    shortDescription: 'A protected Thanesar complex of tombs, gardens and Mughal-period architectural memory.', description: 'Sheikh Chaheli’s Tomb is a monument complex in Thanesar. The official tourism and district pages identify the site as a key Kurukshetra attraction, while the Archaeological Survey of India documents its protected heritage status.', culturalSignificance: 'The complex opens a view onto the many religious and architectural histories held within Thanesar.', historicalContext: 'The tomb is associated with the Sufi figure popularly known as Sheikh Chaheli and sits within Kurukshetra’s layered built heritage.', livingToday: 'Treat the complex as a living place of memory: follow monument rules, avoid climbing or touching surfaces and ask before photographing visitors.',
    image: images.sheikh, gallery: [images.sheikh], imageSource: 'District Administration, Kurukshetra (Government of Haryana)', imageLicense: officialImageLicense, imageSourceUrl: imageSourceUrls.sheikh, sourceUrl: sourceUrls.sheikh, latitude: 29.9767, longitude: 76.8281, coordinateNote: 'Coordinate follows a referenced documentary photograph and is approximate for discovery.', durationMinutes: 120, tags: ['Thanesar', 'tomb', 'Mughal architecture', 'gardens', 'protected monument'], experienceTypes: ['Deep Historical', 'Photography', 'Quiet & Authentic'], verifiedStatus: 'Official source',
  },
  {
    id: 'heritage-sannihit-sarovar', regionId: kurukshetra.id, regionName: kurukshetra.name, name: 'Sannihit Sarovar', slug: 'sannihit-sarovar', category: 'Sacred Landscape', district: 'Kurukshetra', state: 'Haryana',
    shortDescription: 'A sacred sarovar on the Pehowa Road pilgrimage route, with ghats, temples and living ritual practice.', description: 'Sannihit Sarovar is listed by Haryana Tourism and the District Kurukshetra administration as a major sacred water site near Kurukshetra.', culturalSignificance: 'The sarovar’s edges bring together ritual, family memory, local priests and the everyday care of a public religious landscape.', historicalContext: 'The official district account records the site’s pilgrimage associations and nearby temples. The prototype keeps those traditions attributed rather than presenting them as neutral fact.', livingToday: 'Plan around worship, keep ritual spaces unobstructed and ask local guides about appropriate conduct before joining any activity.',
    image: images.sannihit, gallery: [images.sannihit], imageSource: 'District Administration, Kurukshetra (Government of Haryana)', imageLicense: officialImageLicense, imageSourceUrl: imageSourceUrls.sannihit, sourceUrl: sourceUrls.sannihit, latitude: 29.966, longitude: 76.831, coordinateNote: 'Approximate prototype coordinate; confirm the current access point locally.', durationMinutes: 75, tags: ['sarovar', 'water', 'pilgrimage', 'ghats', 'Pehowa Road'], experienceTypes: ['Quiet & Authentic', 'Deep Historical', 'Local Stories'], verifiedStatus: 'Official source', isHidden: true, hiddenReason: 'Less-known in this prototype dataset; access, crowding and ritual context vary by day.',
  },
  {
    id: 'heritage-raja-karna-qila', regionId: kurukshetra.id, regionName: kurukshetra.name, name: 'Raja Karna ka Qila', slug: 'raja-karna-ka-qila', category: 'Archaeological Heritage', district: 'Kurukshetra', state: 'Haryana',
    shortDescription: 'An archaeological mound at Mirzapur that extends the Kurukshetra route beyond its headline landmarks.', description: 'Raja Karna ka Qila, Mirzapur is listed by the District Kurukshetra administration and Haryana Tourism as an archaeological place of interest.', culturalSignificance: 'The mound invites visitors to read the district as a wider archaeological landscape rather than a single monument circuit.', historicalContext: 'The name connects the site to local and epic memory. This prototype does not assign a definitive historical date without a site-specific archaeological source.', livingToday: 'Stay on permitted paths, do not remove material and treat nearby residents as hosts rather than as part of a staged experience.',
    image: images.karna, gallery: [images.karna], imageSource: 'District Administration, Kurukshetra (Government of Haryana)', imageLicense: officialImageLicense, imageSourceUrl: imageSourceUrls.karna, sourceUrl: sourceUrls.karna, latitude: 29.943, longitude: 76.824, coordinateNote: 'Approximate prototype coordinate for Mirzapur; verify exact access before navigation.', durationMinutes: 150, tags: ['archaeology', 'mound', 'Mirzapur', 'local history', 'landscape'], experienceTypes: ['Deep Historical', 'Photography', 'Local Stories'], verifiedStatus: 'Official source', isHidden: true, hiddenReason: 'Less-known in this prototype dataset; site interpretation and access need local verification.',
  },
  {
    id: 'heritage-nabha-house', regionId: kurukshetra.id, regionName: kurukshetra.name, name: 'Nabha House', slug: 'nabha-house', category: 'Architectural Heritage', district: 'Kurukshetra', state: 'Haryana',
    shortDescription: 'A historic Kurukshetra site situated within the district’s dense network of pilgrimage and museum places.', description: 'Nabha House is listed by Haryana Tourism and the District Kurukshetra administration as a place of interest near the city’s museum and temple circuit.', culturalSignificance: 'Its value in this prototype is relational: it helps show how heritage in Kurukshetra is encountered as a connected urban landscape.', historicalContext: 'The record intentionally stays close to the official listing and does not invent a lineage or date that requires specialist verification.', livingToday: 'Check opening arrangements locally, respect nearby worship spaces and avoid treating a working neighbourhood as a set.',
    image: images.nabha, gallery: [images.nabha], imageSource: 'District Administration, Kurukshetra (Government of Haryana)', imageLicense: officialImageLicense, imageSourceUrl: imageSourceUrls.nabha, sourceUrl: sourceUrls.nabha, latitude: 29.973, longitude: 76.846, coordinateNote: 'Approximate prototype coordinate based on the district listing; verify before navigation.', durationMinutes: 90, tags: ['Kurukshetra city', 'built heritage', 'pilgrimage route', 'architecture'], experienceTypes: ['Quiet & Authentic', 'Deep Historical', 'Photography'], verifiedStatus: 'Official source',
  },
  {
    id: 'heritage-sthaneshwar-mahadev', regionId: kurukshetra.id, regionName: kurukshetra.name, name: 'Sthaneshwara Mahadev Temple', slug: 'sthaneshwara-mahadev-temple', category: 'Architecture', district: 'Kurukshetra', state: 'Haryana',
    shortDescription: 'A Thanesar temple precinct where the tank, worship and architecture are part of one living visit.', description: 'Haryana Tourism places Sthaneshwara Mahadev Temple in Kuber Colony, Thanesar, and describes the adjoining tank and the temple’s place in Kurukshetra’s pilgrimage landscape.', culturalSignificance: 'The precinct is maintained by use: prayer, offerings, movement and everyday care matter as much as the visible structure.', historicalContext: 'The official account connects the temple with the sacred geography of Kurukshetra and the story of King Harsh Vardhana. This record keeps that attribution visible.', livingToday: 'Dress modestly, follow temple guidance and leave space for worshippers before taking photographs.',
    image: images.sthaneshwar, gallery: [images.sthaneshwar], imageSource: 'Wikimedia Commons photograph by OjAg', imageLicense: commonsLicense, imageSourceUrl: imageSourceUrls.sthaneshwar, sourceUrl: sourceUrls.sthaneshwar, latitude: 29.9699, longitude: 76.8324, coordinateNote: 'Approximate discovery coordinate for the temple precinct.', durationMinutes: 75, tags: ['temple', 'tank', 'Thanesar', 'worship', 'architecture'], experienceTypes: ['Deep Historical', 'Quiet & Authentic', 'Photography'], verifiedStatus: 'Official source',
  },
  {
    id: 'heritage-rakhigarhi', regionId: hisar.id, regionName: hisar.name, name: 'Ancient Site of Rakhigarhi', slug: 'ancient-site-of-rakhigarhi', category: 'Archaeological Heritage', district: 'Hisar', state: 'Haryana',
    shortDescription: 'A major Harappan archaeological landscape in Haryana’s Hisar district.', description: 'Haryana Tourism places Rakhigarhi in the villages of Rakhikhas and Rakhishahpur, Hisar district, and describes its interconnected mounds, planned settlement remains and excavated material culture.', culturalSignificance: 'Rakhigarhi expands the Haryana story beyond pilgrimage into archaeology, settlement planning, craft production and long-term landscape change.', historicalContext: 'The Haryana Tourism record identifies the site with the mature Harappan phase and gives an approximate period of 2600–1800 BCE. Specialist archaeological interpretation should remain the authority for future detail.', livingToday: 'Follow archaeological-site guidance, do not touch or collect material and check access before travelling to the village setting.',
    image: images.rakhigarhi, gallery: [images.rakhigarhi], imageSource: 'Wikimedia Commons photograph by Durgeshkushvaha', imageLicense: commonsLicense, imageSourceUrl: imageSourceUrls.rakhigarhi, sourceUrl: sourceUrls.rakhigarhi, latitude: 29.17, longitude: 76.07, coordinateNote: 'Approximate prototype coordinate for the Rakhigarhi village site.', durationMinutes: 240, tags: ['archaeology', 'Harappan', 'Hisar', 'mounds', 'settlement'], experienceTypes: ['Deep Historical', 'Photography', 'Local Stories'], verifiedStatus: 'Official source', isHidden: true, hiddenReason: 'Less-known in this prototype dataset; confirm site access and interpretation locally.',
  },
  {
    id: 'heritage-surajkund-crafts-mela', regionId: faridabad.id, regionName: faridabad.name, name: 'Surajkund International Crafts Mela', slug: 'surajkund-international-crafts-mela', category: 'Festival', district: 'Faridabad', state: 'Haryana',
    shortDescription: 'A Haryana Tourism craft fair where handlooms, handicrafts, food and performance meet in Faridabad.', description: 'Haryana Tourism describes the Surajkund Mela as an annual showcase for handicrafts, handlooms, folk traditions and craft demonstrations at Surajkund in Faridabad district.', culturalSignificance: 'The fair creates a public platform for makers and performers, while also raising an important question for responsible discovery: who made the object and how should they be credited?', historicalContext: 'Haryana Tourism records the fair’s origins in 1987 and its development as an international craft event. The event changes by edition, so dates and participants need current verification.', livingToday: 'Use current official dates, credit makers, ask before photographing and remember that a fair is a market and performance space—not a substitute for a community biography.',
    image: images.surajkund, gallery: [images.surajkund], imageSource: 'Wikimedia Commons photograph by Pandey251196', imageLicense: commonsLicense, imageSourceUrl: imageSourceUrls.surajkund, sourceUrl: 'https://haryanatourism.gov.in/fair-and-festivals/surajkund-international-craft-mela/', latitude: 28.4854, longitude: 77.2852, durationMinutes: 240, tags: ['craft', 'handloom', 'festival', 'Faridabad', 'performance'], experienceTypes: ['Cultural & Social', 'Food & Craft', 'Photography'], verifiedStatus: 'Official source',
  },
  {
    id: 'heritage-pinjore-gardens', regionId: panchkula.id, regionName: panchkula.name, name: 'Pinjore Gardens', slug: 'pinjore-gardens', category: 'Architecture', district: 'Panchkula', state: 'Haryana',
    shortDescription: 'A historic garden landscape at the foothills of the lower Shivaliks in Panchkula district.', description: 'Haryana Tourism describes Pinjore Gardens as a seventeenth-century Mughal-style garden complex and lists its tourist complex in Pinjore, Panchkula, Haryana.', culturalSignificance: 'The terraces, water movement and built structures show how landscape design can be part of Haryana’s heritage experience.', historicalContext: 'This record follows the broad period and architectural description provided by Haryana Tourism and avoids adding an unsupported patronage narrative.', livingToday: 'Respect garden rules, avoid blocking working spaces and treat the site as a public landscape rather than a photo-only backdrop.',
    image: images.pinjore, gallery: [images.pinjore], imageSource: 'Wikimedia Commons photograph by Unpetitprole', imageLicense: commonsLicense, imageSourceUrl: imageSourceUrls.pinjore, sourceUrl: sourceUrls.pinjore, latitude: 30.7933, longitude: 76.9133, coordinateNote: 'Coordinate follows the referenced Commons photograph.', durationMinutes: 210, tags: ['garden', 'water design', 'Panchkula', 'Mughal architecture', 'landscape'], experienceTypes: ['Quiet & Slow', 'Photography', 'Deep Historical'], verifiedStatus: 'Official source',
  },
  {
    id: 'heritage-panipat-museum', regionId: panipat.id, regionName: panipat.name, name: 'Panipat Museum', slug: 'panipat-museum', category: 'Museum / Cultural Heritage', district: 'Panipat', state: 'Haryana',
    shortDescription: 'A Haryana museum bringing archaeology, history, art and craft into one public collection.', description: 'Haryana Tourism describes Panipat Museum as a place to encounter antiquities, inscriptions, sculptures, arms and armour, pottery, documents, jewellery and art-and-craft objects from Haryana and beyond.', culturalSignificance: 'The museum makes Haryana’s material history available through objects and interpretation rather than a single monument view.', historicalContext: 'This record follows the museum description published by Haryana Tourism and does not add a battle narrative, collection date or object provenance beyond that official account.', livingToday: 'Check current opening arrangements and photography guidance before visiting; treat displayed objects as a museum collection, not as props.',
    image: images.panipatMuseum, gallery: [images.panipatMuseum], imageSource: 'Jeevant Virasat prototype placeholder', imageLicense: 'Original project SVG; a documentary museum image is pending reuse verification.', imageSourceUrl: imageSourceUrls.panipatMuseum, sourceUrl: sourceUrls.panipatMuseum, latitude: 29.3833, longitude: 76.9667, coordinateNote: 'Approximate Panipat city coordinate; confirm the museum entrance locally.', durationMinutes: 120, tags: ['museum', 'archaeology', 'history', 'art', 'craft', 'Panipat'], experienceTypes: ['Deep Historical', 'Quiet & Authentic', 'Local Stories'], verifiedStatus: 'Official source',
  },
  {
    id: 'heritage-shish-mahal', regionId: gurugram.id, regionName: gurugram.name, name: 'Shish Mahal, Farrukhnagar', slug: 'shish-mahal-farrukhnagar', category: 'Architectural Heritage', district: 'Gurugram', state: 'Haryana',
    shortDescription: 'A Farrukhnagar palace whose mirrors, sandstone court and water channel remain part of Haryana’s built heritage.', description: 'Haryana Tourism describes Shish Mahal in Farrukhnagar as a palace built in 1733, with a sandstone Diwan-e-Aam, mirrors in the wooden ceiling and a water channel with a fountain pool.', culturalSignificance: 'The site connects palace architecture, water design and the historic townscape of Farrukhnagar without requiring an invented personal story.', historicalContext: 'This record stays close to Haryana Tourism’s period and architectural description and identifies the monument as protected by the Haryana Government.', livingToday: 'Confirm access locally, follow monument guidance and avoid treating the protected structure as a photo prop.',
    image: images.shishMahal, gallery: [images.shishMahal], imageSource: 'Wikimedia Commons photograph by Anupamg', imageLicense: commonsLicenseBySa3, imageSourceUrl: imageSourceUrls.shishMahal, sourceUrl: sourceUrls.shishMahal, latitude: 28.45, longitude: 76.82, coordinateNote: 'Approximate Farrukhnagar coordinate from the referenced Commons category.', durationMinutes: 120, tags: ['Farrukhnagar', 'palace', 'architecture', 'water design', 'protected monument'], experienceTypes: ['Deep Historical', 'Photography', 'Quiet & Authentic'], verifiedStatus: 'Official source',
  },
]

function provenanceFor(item: HeritageLocation) {
  const verificationStatus = item.verifiedStatus === 'Official source' ? 'VERIFIED' : item.verifiedStatus === 'Community source' ? 'COMMUNITY_VERIFIED' : item.verifiedStatus === 'Research needed' ? 'PENDING_VERIFICATION' : 'PROTOTYPE'
  return { source: item.imageSource, sourceUrl: item.sourceUrl, verificationStatus, lastUpdated: '2026-08-25', isPrototype: verificationStatus !== 'VERIFIED', imageSource: item.imageSource, imageLicense: item.imageLicense } as const
}

export const heritage: HeritageLocation[] = heritageRecords.map((item): HeritageLocation => ({
  ...item,
  translations: heritageTranslations[item.id],
  provenance: provenanceFor(item),
  ...(item.id === 'heritage-kurukshetra-seasonal-food' ? {
    foodProfile: {
      dishName: 'Kurukshetra Seasonal Food Practice',
      culturalStory: 'A research prompt for documenting seasonal ingredients, household practice, labour and hospitality with local cooks and researchers.',
      weatherSuitability: ['hot', 'warm', 'cold', 'rain', 'all'],
      typicalContext: 'Prototype food-research record; no named dish, kitchen, menu or booking is asserted.',
      isPrototype: true,
      provenance: { ...provenanceFor(item), verificationStatus: 'PENDING_VERIFICATION' as const, isPrototype: true },
    },
  } : {}),
}))
export const hiddenHeritage = heritage.filter((item) => item.isHidden)

export const recognitionExamples: RecognitionExample[] = [
  { id: 'demo-pipli', label: 'Pipli appliqué textile (prototype)', heritageSlug: 'pipli-applique-courtyards', image: prototypeImage('prototype-artisan-textile'), keywords: ['pipli', 'applique', 'textile', 'fabric', 'craft'] },
  { id: 'demo-brahma', label: 'Brahma Sarovar, Kurukshetra', heritageSlug: 'brahma-sarovar', image: images.brahma, keywords: ['brahma', 'sarovar', 'kurukshetra', 'water'] },
  { id: 'demo-jyotisar', label: 'Jyotisar, Kurukshetra', heritageSlug: 'jyotisar', image: images.jyotisar, keywords: ['jyotisar', 'kurukshetra', 'gita', 'sarovar'] },
  { id: 'demo-sheikh', label: 'Sheikh Chaheli’s Tomb', heritageSlug: 'sheikh-chahelis-tomb', image: images.sheikh, keywords: ['sheikh', 'chaheli', 'chilli', 'tomb', 'thanesar'] },
  { id: 'demo-surajkund', label: 'Surajkund Crafts Mela', heritageSlug: 'surajkund-international-crafts-mela', image: images.surajkund, keywords: ['surajkund', 'craft', 'mela', 'faridabad'] },
  { id: 'demo-rakhigarhi', label: 'Rakhigarhi archaeological site', heritageSlug: 'ancient-site-of-rakhigarhi', image: images.rakhigarhi, keywords: ['rakhigarhi', 'harappan', 'hisar', 'archaeology'] },
  { id: 'demo-panipat-museum', label: 'Panipat Museum', heritageSlug: 'panipat-museum', image: images.panipatMuseum, keywords: ['panipat', 'museum', 'archaeology', 'art', 'craft'] },
  { id: 'demo-shish-mahal', label: 'Shish Mahal, Farrukhnagar', heritageSlug: 'shish-mahal-farrukhnagar', image: images.shishMahal, keywords: ['shish', 'sheesh', 'mahal', 'farrukhnagar', 'gurugram', 'palace'] },
]

const prototypeRecord = {
  profileImageSource: 'Jeevant Virasat prototype placeholder', profileImageLicense: 'Original project SVG; no person depicted and no portrait rights implied.', prototypeStatus: 'Unverified prototype record' as const, profileSourceUrl: 'https://haryanatourism.gov.in/', contactMethod: 'Prototype only — no contact request is sent; verify a local introduction before publishing.',
  district: 'Haryana', verificationStatus: 'PROTOTYPE' as const, verificationDate: '2026-08-25', verificationSource: 'Jeevant Virasat demonstration dataset', verifierType: 'Prototype record — no independent verifier', profileVersion: 'v1.0-prototype', source: 'Jeevant Virasat prototype dataset', sourceUrl: 'https://haryanatourism.gov.in/', lastUpdated: '2026-08-25', isPrototype: true,
  provenance: { source: 'Jeevant Virasat prototype dataset', sourceUrl: 'https://haryanatourism.gov.in/', verificationStatus: 'PROTOTYPE' as const, lastUpdated: '2026-08-25', isPrototype: true, imageSource: 'Jeevant Virasat prototype placeholder', imageLicense: 'Original project SVG; no person depicted and no portrait rights implied.' },
}

const artisanRecords = [
  { ...prototypeRecord, id: 'artisan-pipli-applique', name: 'Pipli Appliqué Collective', slug: 'pipli-applique-collective', craft: 'Appliqué textile', regionId: kurukshetra.id, regionName: kurukshetra.name, location: 'Pipli, Kurukshetra district, Haryana', biography: 'Demonstration record for a Pipli appliqué practice. The individual makers, consent status and workshop details are intentionally not published until community review.', craftStory: 'A prototype prompt about cut cloth, colour and shared workshop knowledge—not an attributed personal biography.', profileImage: prototypeImage('prototype-artisan-textile'), gallery: [prototypeImage('prototype-artisan-textile')], specialties: ['Cut cloth', 'Layered colour', 'Workshop context'], relatedHeritageIds: ['heritage-pipli-craft'] },
  { ...prototypeRecord, id: 'artisan-thanesar-terracotta', name: 'Thanesar Terracotta Practice', slug: 'thanesar-terracotta-practice', craft: 'Terracotta pottery', regionId: kurukshetra.id, regionName: kurukshetra.name, location: 'Thanesar, Kurukshetra district, Haryana', biography: 'Demonstration record for a clay and vessel-making practice. No individual artisan is being represented as verified.', craftStory: 'A prototype prompt about clay preparation, wheel work and everyday vessels that requires a local maker interview.', profileImage: prototypeImage('prototype-artisan-pottery'), gallery: [prototypeImage('prototype-artisan-pottery')], specialties: ['Clay preparation', 'Household vessels', 'Process demonstration'], relatedHeritageIds: ['heritage-sheikh-chahelis-tomb'] },
  { ...prototypeRecord, id: 'artisan-hisar-embroidery', name: 'Hisar Needlework Circle', slug: 'hisar-needlework-circle', craft: 'Textile embroidery', regionId: hisar.id, regionName: hisar.name, location: 'Hisar district, Haryana', biography: 'Demonstration record for a Haryana textile practice. Names, photographs and credentials are withheld pending consent and community review.', craftStory: 'A prototype prompt about motif, cloth and memory that should be completed with the people who practise it.', profileImage: prototypeImage('prototype-artisan-embroidery'), gallery: [prototypeImage('prototype-artisan-embroidery')], specialties: ['Embroidery', 'Motif memory', 'Textile care'], relatedHeritageIds: ['heritage-rakhigarhi'] },
  { ...prototypeRecord, id: 'artisan-rohtak-ragini', name: 'Rohtak Ragini Performance Circle', slug: 'rohtak-ragini-performance-circle', craft: 'Ragini performance', regionId: haryana.id, regionName: haryana.name, location: 'Rohtak district, Haryana', biography: 'Demonstration record for a Haryanvi sung storytelling practice. It is not a profile of a named performer.', craftStory: 'A prototype prompt about voice, metre, audience and contemporary local storytelling that needs performer-led documentation.', profileImage: prototypeImage('prototype-artisan-ragini'), gallery: [prototypeImage('prototype-artisan-ragini')], specialties: ['Oral history', 'Performance', 'Community events'], relatedHeritageIds: [] },
  { ...prototypeRecord, id: 'artisan-kurukshetra-moonj', name: 'Kurukshetra Moonj Basketry Collective', slug: 'kurukshetra-moonj-basketry-collective', craft: 'Fibre basketry', regionId: kurukshetra.id, regionName: kurukshetra.name, location: 'Kurukshetra district, Haryana', biography: 'Demonstration record for a fibre preparation and basketry practice. No individual maker or income claim is attached to this entry.', craftStory: 'A prototype prompt about gathering, drying and weaving fibre that needs consented maker documentation.', profileImage: prototypeImage('prototype-artisan-basketry'), gallery: [prototypeImage('prototype-artisan-basketry')], specialties: ['Fibre preparation', 'Storage baskets', 'Maker circles'], relatedHeritageIds: [] },
  { ...prototypeRecord, id: 'artisan-surajkund-makers', name: 'Surajkund Maker Network (prototype)', slug: 'surajkund-maker-network', craft: 'Craft fair practice', regionId: faridabad.id, regionName: faridabad.name, location: 'Surajkund, Faridabad district, Haryana', biography: 'Demonstration record linked to the public craft-fair context described by Haryana Tourism. It does not identify or speak for any participating maker.', craftStory: 'A prototype prompt about attribution, market access and craft demonstrations at a public fair.', profileImage: prototypeImage('prototype-artisan-textile'), gallery: [prototypeImage('prototype-artisan-textile')], specialties: ['Handicrafts', 'Handlooms', 'Maker attribution'], relatedHeritageIds: ['heritage-surajkund-crafts-mela'] },
]

export const artisans: Artisan[] = artisanRecords.map((item) => {
  const locationParts = item.location.split(',').map((part) => part.trim())
  const district = locationParts.find((part) => /district/i.test(part))?.replace(/\s+district/i, '') ?? locationParts[locationParts.length - 2] ?? 'Haryana'
  const provenance = { ...item.provenance, source: item.source, sourceUrl: item.sourceUrl, verificationStatus: item.verificationStatus, lastUpdated: item.lastUpdated, isPrototype: item.isPrototype }
  return { ...item, district, provenance }
})

export const products: Product[] = [
  {
    id: 'product-pipli-applique-panel', name: 'Pipli appliqué textile panel', slug: 'pipli-applique-textile-panel', craft: 'Appliqué textile', originDistrict: 'Kurukshetra', regionName: 'Kurukshetra',
    description: 'A prototype product record for cut cloth, layered colour and hand-stitching in the Pipli craft prompt.', culturalStory: 'The platform keeps the product linked to the craft record while leaving maker attribution, current availability and price validation open.', productionProcess: ['Cut cloth shapes with local guidance.', 'Layer and stitch the design.', 'Document maker attribution and consent before publication.'], image: prototypeImage('prototype-artisan-textile'), material: 'Layered cloth and thread', productionTimeMinutes: 240, availability: 'Prototype reference only — no order or booking is available.', referencePrice: { kind: 'PROTOTYPE_REFERENCE', label: 'Reference price — prototype: ₹400–₹1,200', min: 400, max: 1200, unit: 'per panel' }, estimatedCost: 620, verificationStatus: 'PROTOTYPE', isPrototype: true, source: 'Jeevant Virasat prototype dataset', sourceUrl: 'https://haryanatourism.gov.in/destinations/kurukshetra/', lastUpdated: '2026-08-25', provenance: { source: 'Jeevant Virasat prototype dataset', sourceUrl: 'https://haryanatourism.gov.in/destinations/kurukshetra/', verificationStatus: 'PROTOTYPE', lastUpdated: '2026-08-25', isPrototype: true, imageSource: 'Jeevant Virasat prototype placeholder', imageLicense: 'Original project SVG; no person depicted.' }, artisanId: 'artisan-pipli-applique', relatedHeritageIds: ['heritage-pipli-craft'],
  },
  {
    id: 'product-thanesar-terracotta-vessel', name: 'Thanesar terracotta vessel', slug: 'thanesar-terracotta-vessel', craft: 'Terracotta pottery', originDistrict: 'Kurukshetra', regionName: 'Kurukshetra',
    description: 'A prototype product record for a household vessel-making practice; no individual maker is represented as verified.', culturalStory: 'This product is a documentation prompt for clay preparation, wheel work and everyday use, not a marketplace listing.', productionProcess: ['Prepare and shape clay with a consented maker.', 'Dry and fire the vessel according to local practice.', 'Record the process and maker attribution before public publication.'], image: prototypeImage('prototype-artisan-pottery'), material: 'Clay', productionTimeMinutes: 180, availability: 'Prototype reference only — local availability is unknown.', referencePrice: { kind: 'PROTOTYPE_REFERENCE', label: 'Reference price — prototype: ₹250–₹800', min: 250, max: 800, unit: 'per vessel' }, estimatedCost: 310, verificationStatus: 'PROTOTYPE', isPrototype: true, source: 'Jeevant Virasat prototype dataset', sourceUrl: 'https://haryanatourism.gov.in/', lastUpdated: '2026-08-25', provenance: { source: 'Jeevant Virasat prototype dataset', sourceUrl: 'https://haryanatourism.gov.in/', verificationStatus: 'PROTOTYPE', lastUpdated: '2026-08-25', isPrototype: true, imageSource: 'Jeevant Virasat prototype placeholder', imageLicense: 'Original project SVG; no person depicted.' }, artisanId: 'artisan-thanesar-terracotta', relatedHeritageIds: [],
  },
]

const livelihoodInputs = artisans.flatMap((artisan, artisanIndex) => [
  { artisanId: artisan.id, period: '2026-05', productionUnits: 18 + artisanIndex * 2, unitsSold: 12 + artisanIndex, averageSellingPrice: 650 + artisanIndex * 40, materialCost: 2600 + artisanIndex * 150, labourCost: 3200 + artisanIndex * 180, transportCost: 700, otherCosts: 450, source: 'Illustrative prototype data', isPrototype: true },
  { artisanId: artisan.id, period: '2026-06', productionUnits: 21 + artisanIndex * 2, unitsSold: 15 + artisanIndex, averageSellingPrice: 680 + artisanIndex * 40, materialCost: 2900 + artisanIndex * 150, labourCost: 3500 + artisanIndex * 180, transportCost: 760, otherCosts: 500, source: 'Illustrative prototype data', isPrototype: true },
  { artisanId: artisan.id, period: '2026-07', productionUnits: 24 + artisanIndex * 2, unitsSold: 17 + artisanIndex, averageSellingPrice: 700 + artisanIndex * 40, materialCost: 3200 + artisanIndex * 150, labourCost: 3700 + artisanIndex * 180, transportCost: 800, otherCosts: 520, source: 'Illustrative prototype data', isPrototype: true },
  { artisanId: artisan.id, period: '2026-08', productionUnits: 20 + artisanIndex * 2, unitsSold: 14 + artisanIndex, averageSellingPrice: 720 + artisanIndex * 40, materialCost: 3000 + artisanIndex * 150, labourCost: 3600 + artisanIndex * 180, transportCost: 780, otherCosts: 510, source: 'Illustrative prototype data', isPrototype: true },
])

export const livelihoodRecords: LivelihoodRecord[] = livelihoodInputs.map(calculateLivelihood)

const storyRecords: Story[] = [
  { id: 'story-water-memory', title: 'What a Kurukshetra Waterbody Holds', slug: 'what-a-kurukshetra-waterbody-holds', regionId: kurukshetra.id, regionName: kurukshetra.name, category: 'Landscape & memory', excerpt: 'Brahma Sarovar and Sannihit Sarovar show how a water body can be sacred, civic and deeply local at the same time.', image: images.brahma, content: ['The water edge is not only a view. At Kurukshetra’s sarovars, visitors encounter worship, walking, local guidance and the practical work of keeping a public place usable.', 'The official district and tourism references name Brahma Sarovar and Sannihit Sarovar among the area’s important heritage places. A responsible platform should preserve that context while leaving room for local interpretation.', 'The prototype therefore treats the image as an invitation to look closer—not as proof of a universal visitor experience.'], relatedHeritageIds: ['heritage-brahma-sarovar', 'heritage-sannihit-sarovar'], relatedArtisanIds: ['artisan-kurukshetra-moonj'] },
  { id: 'story-jyotisar', title: 'At Jyotisar, Context Comes First', slug: 'at-jyotisar-context-comes-first', regionId: kurukshetra.id, regionName: kurukshetra.name, category: 'Sacred landscape', excerpt: 'A sacred site asks the visitor to notice water, trees, ritual and interpretation before reaching for a camera.', image: images.jyotisar, content: ['Jyotisar is named by Haryana Tourism and the District Kurukshetra administration as a pilgrimage place on the bank of Jyotisar Sarovar.', 'Its meaning is carried through the traditions and practices that bring people there. The platform can point to those layers, but it should not replace the site’s own voices with a single polished caption.', 'Begin with attention: read the local guidance, ask before photographing and let the visit remain more than an identification result.'], relatedHeritageIds: ['heritage-jyotisar'], relatedArtisanIds: [] },
  { id: 'story-thanesar-architecture', title: 'Thanesar Is More Than One Monument', slug: 'thanesar-is-more-than-one-monument', regionId: kurukshetra.id, regionName: kurukshetra.name, category: 'Built heritage', excerpt: 'Sheikh Chaheli’s Tomb and Sthaneshwara Mahadev Temple make the city’s architectural and religious layers visible together.', image: images.sheikh, content: ['Thanesar’s heritage is encountered as a network: tombs, temples, tanks, gardens and streets that remain part of a working city.', 'The official references for Sheikh Chaheli’s Tomb and Sthaneshwara Mahadev Temple describe distinct places with different histories and living practices. Keeping those records separate is part of respectful discovery.', 'The prototype links them only as nearby context, never as interchangeable images or stories.'], relatedHeritageIds: ['heritage-sheikh-chahelis-tomb', 'heritage-sthaneshwar-mahadev'], relatedArtisanIds: [] },
  { id: 'story-surajkund-makers', title: 'The Fair Is a Marketplace, Too', slug: 'the-fair-is-a-marketplace-too', regionId: faridabad.id, regionName: faridabad.name, category: 'Craft & community', excerpt: 'Surajkund makes craft visible at scale, which makes maker credit and consent even more important.', image: images.surajkund, content: ['Haryana Tourism describes the Surajkund International Crafts Mela as a platform for handicrafts, handlooms, folk traditions and demonstrations in Faridabad.', 'A visitor may see a colourful object first. A responsible story keeps asking who made it, what the maker wants shared and how a platform can direct attention without inventing a biography.', 'This entry stays deliberately general until individual makers opt into a verified profile.'], relatedHeritageIds: ['heritage-surajkund-crafts-mela'], relatedArtisanIds: ['artisan-surajkund-makers'] },
  { id: 'story-rakhigarhi', title: 'Reading a Site Through Its Mounds', slug: 'reading-a-site-through-its-mounds', regionId: hisar.id, regionName: hisar.name, category: 'Archaeology & place', excerpt: 'Rakhigarhi asks visitors to look at settlement, material and landscape together.', image: images.rakhigarhi, content: ['Haryana Tourism describes Rakhigarhi as a five-mound archaeological site in Hisar district with evidence of planned settlement, drainage, ceramics and other material culture.', 'The site is not a single object to be consumed in a quick photograph. It is a landscape that needs archaeological care, local access guidance and time.', 'The prototype keeps its claims close to the official listing and leaves specialist interpretation open for future review.'], relatedHeritageIds: ['heritage-rakhigarhi'], relatedArtisanIds: [] },
  { id: 'story-pinjore', title: 'A Garden Designed as a Journey', slug: 'a-garden-designed-as-a-journey', regionId: panchkula.id, regionName: panchkula.name, category: 'Architecture & landscape', excerpt: 'Pinjore’s terraces and water movement make the landscape itself part of the architecture.', image: images.pinjore, content: ['Haryana Tourism describes Pinjore Gardens as a seventeenth-century Mughal-style garden complex in Panchkula district.', 'The terraces, water and built structures are experienced in sequence. Looking slowly helps the visitor notice how a garden can organise movement and pause.', 'The platform presents the site as a place to observe with care, not as a licence to ignore garden rules or the people sharing it.'], relatedHeritageIds: ['heritage-pinjore-gardens'], relatedArtisanIds: [] },
  { id: 'story-panipat-museum', title: 'A Museum for Haryana’s Many Histories', slug: 'a-museum-for-haryanas-many-histories', regionId: panipat.id, regionName: panipat.name, category: 'Museum & memory', excerpt: 'Panipat Museum brings archaeology, history, art and craft into a public collection without reducing Haryana to one monument.', image: images.panipatMuseum, content: ['Haryana Tourism describes Panipat Museum as a place for antiquities, inscriptions, sculptures, arms and armour, pottery, documents, jewellery and art-and-craft objects.', 'A museum visit changes the scale of discovery: objects from different Haryana districts can sit in one room while retaining their own material histories.', 'The prototype keeps this story close to the official museum description and leaves individual object provenance to the museum’s own interpretation.'], relatedHeritageIds: ['heritage-panipat-museum'], relatedArtisanIds: [] },
  { id: 'story-farrukhnagar-mirrors-and-water', title: 'Farrukhnagar’s Mirrors and Water', slug: 'farrukhnagars-mirrors-and-water', regionId: gurugram.id, regionName: gurugram.name, category: 'Built heritage', excerpt: 'Shish Mahal makes mirrors, sandstone and water design visible in Farrukhnagar’s protected architectural landscape.', image: images.shishMahal, content: ['Haryana Tourism describes Shish Mahal as a palace built in 1733 with a sandstone Diwan-e-Aam, mirrors and a water channel with a fountain pool.', 'The details are architectural evidence, not an invitation to fill the gaps with an invented royal biography. A careful visit starts with the structure and the town around it.', 'The image is credited to Wikimedia Commons and the record keeps access and current site conditions open for local verification.'], relatedHeritageIds: ['heritage-shish-mahal'], relatedArtisanIds: [] },
]

export const stories = storyRecords.map((item) => ({ ...item, translations: storyTranslations[item.id] }))

export const sampleTrails: Trail[] = [
  { id: 'trail-water-and-sacred-memory', name: 'Water & Sacred Memory in Kurukshetra', regionId: kurukshetra.id, regionName: kurukshetra.name, duration: 285, interests: ['Local Stories', 'History'], experienceType: 'Deep Historical', timeChoice: 'Half day', createdAt: '2026-01-01T00:00:00.000Z', stops: [heritage[0], heritage[5], heritage[3]].map((stop, index) => ({ ...stop, matchReason: ['Begin with the scale of a shared sacred water edge.', 'Follow the district’s connected sarovar tradition.', 'End at a pilgrimage landscape where interpretation and practice meet.'][index], distanceFromPreviousKm: index === 0 ? undefined : 4.5 })) },
  { id: 'trail-thanesar-layers', name: 'Thanesar’s Built Heritage Layers', regionId: kurukshetra.id, regionName: kurukshetra.name, duration: 285, interests: ['Architecture', 'History'], experienceType: 'Deep Historical', timeChoice: 'Half day', createdAt: '2026-01-01T00:00:00.000Z', stops: [heritage[4], heritage[8], heritage[7]].map((stop, index) => ({ ...stop, matchReason: ['Start with a protected tomb complex and its gardens.', 'Read a temple precinct through daily use and architecture.', 'Close with a quieter built-heritage stop in the city circuit.'][index], distanceFromPreviousKm: index === 0 ? undefined : 2.8 })) },
  { id: 'trail-haryana-sites-beyond-kurukshetra', name: 'Haryana Sites Beyond the Headline', regionId: haryana.id, regionName: haryana.name, duration: 450, interests: ['History', 'Photography'], experienceType: 'Quiet & Authentic', timeChoice: 'Full day', createdAt: '2026-01-01T00:00:00.000Z', stops: [heritage[9], heritage[10]].map((stop, index) => ({ ...stop, matchReason: ['Read Haryana through an archaeological landscape.', 'Follow craft, handloom and performance into a public fair setting.'][index], distanceFromPreviousKm: index === 0 ? undefined : 185 })) },
]

export const demoData = { regions, heritage, artisans, stories, products, livelihoodRecords, sampleTrails }
